### ISSUE TITLE
security issue in get-ip-range

### ISSUE THREAD

**Issue by yaniv-checkmarx** [JoeScho/get-ip-range#16]
Hello,
My name is Yaniv and I’m a security analystat Checkmarx's CxSCA group.
Checkmarx is a global software security company aiming for the safer usage of code and libraries. 
I recently found a security issue in get-ip-range.
I couldn’t reach any relevant maintainer to disclose this issue to, and I would appreciate you referring me to the right contact.

Please fell free to reach me at ScaAppSec@checkmarx.com.

Best regards,
Yaniv.

**Comment by JoeScho** [comment]
Hi Yaniv,

Per my email this is now fixed

Joe
